/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#703533",
        "surface-container-high": "#e9e8e4",
        "secondary": "#4d6357",
        "on-secondary-fixed-variant": "#354c40",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f5f4f0",
        "surface-container": "#efeeea",
        "inverse-primary": "#96d4b3",
        "on-primary-fixed": "#002114",
        "on-secondary-container": "#526a5d",
        "outline-variant": "#bfc9c1",
        "tertiary-fixed": "#ffdad7",
        "primary": "#002f1e",
        "on-background": "#1b1c1a",
        "primary-fixed-dim": "#96d4b3",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#4a1817",
        "on-surface-variant": "#404943",
        "surface": "#faf9f5",
        "error-container": "#ffdad6",
        "secondary-fixed": "#cfe9d8",
        "error": "#ba1a1a",
        "secondary-container": "#cfe9d8",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c1a",
        "surface-dim": "#dbdad6",
        "on-error": "#ffffff",
        "surface-variant": "#e3e2df",
        "surface-bright": "#faf9f5",
        "on-primary-container": "#79b697",
        "tertiary-container": "#652d2b",
        "primary-fixed": "#b1f0ce",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2df",
        "inverse-surface": "#30312e",
        "secondary-fixed-dim": "#b3ccbd",
        "outline": "#707973",
        "on-primary-fixed-variant": "#0f5138",
        "on-secondary": "#ffffff",
        "surface-tint": "#2d694f",
        "on-tertiary-fixed": "#390b0b",
        "on-secondary-fixed": "#092016",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-container": "#e39590",
        "primary-container": "#004830",
        "background": "#faf9f5",
        "inverse-on-surface": "#f2f1ed",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Sarabun", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

